@startuml
!theme mars
autonumber

actor "Simulator / Car" as car
participant "Spring Boot\n(Ingestion Service)" as java
database "PostgreSQL\n(trip_logs)" as db_raw
queue "RabbitMQ" as mq
participant "FastAPI\n(ML Worker)" as python
database "PostgreSQL\n(driver_scores)" as db_score

== Phase 1: Ingestion (Fast) ==
car -> java: POST /api/telemetry\n{JSON Payload 5MB}
activate java

java -> db_raw: INSERT INTO trip_logs (id, blob, status='PENDING')
activate db_raw
db_raw --> java: Success
deactivate db_raw

java -> mq: Publish Message\n{trip_id: "uuid-123"}
java --> car: 202 Accepted\n{"trip_id": "uuid-123"}
deactivate java
note right: Client is released here.\nDoes not wait for ML.

== Phase 2: Processing (Async) ==
mq -> python: Consume Message\n{trip_id: "uuid-123"}
activate python

python -> db_raw: SELECT blob FROM trip_logs WHERE id...
activate db_raw
db_raw --> python: Returns {JSON Payload}
deactivate db_raw

python -> python: NumPy Analysis\n(Vector Calculations)

python -> db_score: INSERT INTO driver_scores (score, metrics...)
activate db_score
db_score --> python: Success
deactivate db_score

python -> db_raw: UPDATE trip_logs SET status='COMPLETED'
deactivate python

@enduml