@startuml telemetry_components
!theme mars

package "FleetFlow Cluster" {

    ' The Ingestion Side
    component "FastAPI Ingester" as api_service {
        port "HTTP /api/v1/telemetry" as ingester
        database "SQLAlchemy" as api_orm
    }

    ' The Analysis Side
    component "Python Worker" as worker_service {
        component "RabbitMQ Consumer" as worker
        component "NumPy Analyzer" as math
        database "SQLAlchemy" as worker_orm
    }

    ' Middleware
    queue "RabbitMQ" as queue {
        label "queue: telemetry_analysis"
    }

    ' Database
    database "PostgreSQL" as db {
        folder "Schema: telemetry" {
            [trip_data_raw]
            [driver_scores]
        }
    }
}

' Data Flow
[Car / Simulator] --> ingester : 1. POST JSON Blob
api_service --> [trip_data_raw] : 2. Save Heavy JSON (Claim Check)
api_service -r-> queue : 3. Publish Trip ID (Signal)

queue -r-> worker : 4. Consume Trip ID
worker --> [trip_data_raw] : 5. Fetch Heavy JSON
worker --> math : 6. Calculate Score
math --> [driver_scores] : 7. Insert Result

@enduml